### ISSUE TITLE
Conda-forge package for fsl

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/fslpy-feedstock#13]
I'm sorry that this is most likely the wrong place to ask, but I couldn't find a better one - feel free to redirect me.

Is anyone considering a conda-forge package for `fsl` itself, so that `fslpy` can depend on it directly?

**Comment by pauldmccarthy** [comment]
Hey @duncanmmacleod, sorry for the delay. No, there are no immediate plans to add `fsl` to  conda-forge, so currently you would need to install FSL manually.

Perhaps in the future, FSL will become more modular, so that it could be managed by a more conventional package manager such as `conda`. But this is unlikely to be soon.

**Comment by pauldmccarthy** [comment]
As of 6.0.6, FSL is now conda-based - we are hosting FSL packages at our own conda channel: https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/

**Comment by michaelkarlcoleman** [comment]
@pauldmccarthy This looks _really_ nice.  We're an HPC environment using SLURM, and currently on FSL 6.0.1.  The `fsl_sub` script was hacked to support SLURM, for the most part.  I haven't looked closely, but it appears that the "config file" approach will work for us.

As a detail, users in our environment won't be able to modify the conda installation tree at all.  So, the config file has to live elsewhere.  My read is that we can do this with `$FSLSUB_CONF`.

Not sure whether we'd use `fsl_sub` for other purposes, but if it's sufficiently general, it's certainly a possibility.  It would be a nice utility for broad use.

**Comment by michaelkarlcoleman** [comment]
Not seeing any obvious way to file issues against this repo, but I'll note that this line blows up when I try it at our site.  I think the prior line has a typo or logic error.  https://git.fmrib.ox.ac.uk/fsl/fsl_sub_plugin_slurm/-/blob/master/fsl_sub_plugin_slurm/__init__.py#L926

```
(fsl-bet2-20230227) mcolema5@talapas-ln1 ~ 175$ fsl_sub_config slurm
Traceback (most recent call last):
  File "/packages/miniconda/20190102/envs/fsl-bet2-20230227/bin/fsl_sub_config", line 10, in <module>
    sys.exit(example_config())
             ^^^^^^^^^^^^^^^^
  File "/packages/miniconda/20190102/envs/fsl-bet2-20230227/lib/python3.11/site-packages/fsl_sub/cmdline.py", line 706, in example_config
    yaml_config = e_conf(options.plugin)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/packages/miniconda/20190102/envs/fsl-bet2-20230227/lib/python3.11/site-packages/fsl_sub/config.py", line 233, in example_config
    queue_defs = get_plugin_queue_defs(method)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/packages/miniconda/20190102/envs/fsl-bet2-20230227/lib/python3.11/site-packages/fsl_sub/utils.py", line 144, in get_plugin_queue_defs
    return PLUGINS[grid_module].build_queue_defs()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/packages/miniconda/20190102/envs/fsl-bet2-20230227/lib/python3.11/site-packages/fsl_sub_plugin_slurm/__init__.py", line 1083, in build_queue_defs
    gres = _get_queue_gres(q)
           ^^^^^^^^^^^^^^^^^^
  File "/packages/miniconda/20190102/envs/fsl-bet2-20230227/lib/python3.11/site-packages/fsl_sub_plugin_slurm/__init__.py", line 926, in _get_queue_gres
    sub_g, _ = sub_g.split('(')
    ^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

```
(fsl-bet2-20230227) mcolema5@talapas-ln1 ~ 173$ sinfo -h -p short -o '%G'
(null)
(fsl-bet2-20230227) mcolema5@talapas-ln1 ~ 174$ sinfo -h -p gpu -o '%G'
gpu:tesla_k80:4(S:0-1)
```

See also: https://git.fmrib.ox.ac.uk/fsl/fsl_sub_plugin_slurm/-/commit/cfb59c033a94c7ca39b140a6641fe7b82c0fcfb4

**Comment by pauldmccarthy** [comment]
@michaelkarlcoleman I think you're right - looks to me like it should be `if '(' in sub_g:` - I'll pass this on to Duncan
